name: zenius_redesign
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.6+3
  path_provider: ^1.6.5
  flutter_bloc: ^3.2.0
  meta: ^1.1.8
  equatable: ^1.1.1
  step_progress_indicator: ^0.2.4+7
  permission_handler: 5.0.1+2
  cached_network_image: ^2.0.0
  carousel_slider: ^3.0.0
  intl: ^0.16.1
  timeago: ^2.0.26
  package_info: ^0.4.0+16
  shimmer: ^1.1.0
  pull_to_refresh: ^1.5.7
  device_info: '>=0.4.2+4 <2.0.0'
  flare_flutter: ^2.0.1
  photo_view: ^0.9.2
  bottom_navigation_badge: ^1.0.3
  fluttertoast: ^3.1.3
  font_awesome_flutter: ^8.7.0
  flutter_html: ^0.11.1
  share: ^0.6.3+1
  pinput: ^0.1.10
  grouped_buttons: ^1.0.4
  focus_detector: ^1.0.2
#  flutter_cupertino_date_picker: ^1.0.26+2
  flutter_full_pdf_viewer: ^1.0.6
  progress_button: "^0.0.2"
  file_picker: ^1.11.0+2
  datetime_picker_formfield:
  http: any
  flutter_masked_text: 0.8.0
  flushbar:
  table_calendar: ^2.3.2
  fl_chart: ^0.12.2
  bubble_tab_indicator: "^0.1.4"
  percent_indicator: ^2.1.9+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
      - asset: fonts/Roboto.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
